### ISSUE TITLE
When to release the code.

### ISSUE THREAD

**Issue by xiaoiker** [edongdongchen/DDN#1]
Hey, this work is interesting. When do you plan to release the code?

Best.

**Comment by edongdongchen** [comment]
> Hey, this work is interesting. When do you plan to release the code?
> 
> Best.

Hi, sorry for the late reply, please find the updated code. Thanks!

**Comment by edongdongchen** [comment]
> Hey, this work is interesting. When do you plan to release the code?
> 
> Best.
