### ISSUE TITLE
Something wrong with the final plot

### ISSUE THREAD

**Issue by chuan1093** [edongdongchen/DDN#2]
When I run your `sr_test.py`, I got the following plot. It seems that something is wrong with the plotting code. Would you kindly fix this small bug?
![image](https://user-images.githubusercontent.com/41619684/95675729-f32d8980-0beb-11eb-981f-8cba4325c17e.png)

**Comment by edongdongchen** [comment]
> When I run your `sr_test.py`, I got the following plot. It seems that something is wrong with the plotting code. Would you kindly fix this small bug?


Hello, I just tried and checked the code again. I didn't meet the errors you just illustrated here (see below result).  Can you please try to report and direct plot the Y_ddn to check if the reconstruction is generated correctly? e.g. plt.imshow(Y_ddn). 
![image](https://user-images.githubusercontent.com/43349309/95693152-c5b00280-0c22-11eb-9c32-c28d2fb556a9.png)

**Comment by ChaoWei0606** [comment]
Hello,when I perform the train code, I have a question as follws: NorImplementedError: input error:only 3D, 4D, and 5D input Tensors support(gor 1D) for the modes: | linear | bilinear | bicubic | trilinear (got bicubic)
Please you can help me, thanks!
![Wrong](https://user-images.githubusercontent.com/38529252/95992406-7ce58d00-0e60-11eb-9182-767cb7e2399e.png)

**Comment by edongdongchen** [comment]
> Hello,when I perform the train code, I have a question as follws: NorImplementedError: input error:only 3D, 4D, and 5D input Tensors support(gor 1D) for the modes: | linear | bilinear | bicubic | trilinear (got bicubic)
> Please you can help me, thanks!

Hi, what's the dimension of your training data x? It seems your input x is a 1D tensor. If so, you need to feed a 4D image tensor (NCHW) instead. let me know if it makes sense.

**Comment by ChaoWei0606** [comment]
@edongdongchen hello, my train data is image

**Comment by edongdongchen** [comment]
> @edongdongchen hello, my train data is image

@ChaoWei0606 sorry, I can't open your uploaded image. Can you please upload it again and print the shape of x there (just before line 48 in operators.py)?

**Comment by ChaoWei0606** [comment]
OK，thank you！I try to your method！



---Original---

**Comment by chuan1093** [comment]
I've figure it out. Thanks for answering.
