### ISSUE TITLE
Problem with train_loader

### ISSUE THREAD

**Issue by kristiantorres** [edongdongchen/DDN#3]
Hi Dongdong, 

  Excellent work! I enjoyed reading your paper and am trying to reproduce the Super Resolution results. I downloaded the BSDS300 dataset from [here](https://www2.eecs.berkeley.edu/Research/Projects/CS/vision/bsds/BSDS300-images.tgz). However, I am getting the following output when I run `python sr_train.py`:
```
  start training...
  Traceback (most recent call last):
    File "sr_train.py", line 158, in <module>
      train(args)
    File "sr_train.py", line 85, in train
      for x, m, y in train_loader:
  ValueError: not enough values to unpack (expected 3, got 2)

```
I would like to know what is `m` in the for loop (line 85 in sr_train.py). 

Thanks!

**Comment by edongdongchen** [comment]
> Hi Dongdong,
> 
> Excellent work! I enjoyed reading your paper and am trying to reproduce the Super Resolution results. I downloaded the BSDS300 dataset from [here](https://www2.eecs.berkeley.edu/Research/Projects/CS/vision/bsds/BSDS300-images.tgz). However, I am getting the following output when I run `python sr_train.py`:
> 
> ```
>   start training...
>   Traceback (most recent call last):
>     File "sr_train.py", line 158, in <module>
>       train(args)
>     File "sr_train.py", line 85, in train
>       for x, m, y in train_loader:
>   ValueError: not enough values to unpack (expected 3, got 2)
> ```
> 
> I would like to know what is `m` in the for loop (line 85 in sr_train.py).
> 
> Thanks!

Hi Kris,

Thanks for pointing out this. Sorry there was a copy/paste error in line 85 (actually m was defined and used for another MRF experiment), I just updated line 85, please have a try and let me know if it doesn't work. 

All the best!
